version: "3.4"

services:
   liquidity-database:
      image: postgres:9.6
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=test
         - POSTGRES_DB=liquidity
      restart: always
      volumes:
         - ./pgsql/cloud_db.pgsql:/docker-entrypoint-initdb.d/1-schema.sql
         - ./pgsql/add-migrations-table.pgsql:/docker-entrypoint-initdb.d/2-schema.sql
         - liquidity-db-data:/var/lib/postgresql/data/
      networks:
         - liquidity-backend-network
      expose:
         - "5432"

   liquidity-web-api:
      build: .
      entrypoint: crypto-liquidity-web-api
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network
      expose:
         - "8000"

   liquidity-service-test:
      build: .
      entrypoint: crypto-liquidity-db-test
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - SERVER_ADDRESS=http://liquidity-web-api:8000
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

networks:
   liquidity-backend-network:
      driver: bridge

volumes:
   liquidity-db-data:
