version: "3.4"

services:
   liquidity-database:
      image: postgres:9.6
      container_name: database
      environment:
         - POSTGRES_PASSWORD=test
         - POSTGRES_USER=test
         - POSTGRES_DB=liquidity
      restart: always
      volumes:
         - ./crypto-liquidity-db/pgsql/cloud_db.pgsql:/docker-entrypoint-initdb.d/1-schema.sql
         - ./crypto-liquidity-db/pgsql/add-migrations-table.pgsql:/docker-entrypoint-initdb.d/2-schema.sql
         - liquidity-db-data:/var/lib/postgresql/data/
      networks:
         - liquidity-backend-network
      expose:
         - "5432"

   liquidity-service-test:
      restart: never
      build: .
      entrypoint: crypto-liquidity-test
      container_name: liquidity-service-test
      links:
         - liquidity-database
      depends_on:
         - liquidity-database
      environment:
         - DATABASE_URL=postgresql://test:test@liquidity-database:5432/liquidity?sslmode=disable
      networks:
         - liquidity-backend-network

networks:
   liquidity-backend-network:
      driver: bridge

volumes:
   liquidity-db-data:
