name:                crypto-liquidity-db
version:             0.1.0.0
github:              "runeksvendsen/crypto-liquidity-db"
license:             BSD3
author:              "Rune K. Svendsen"
maintainer:          "runesvend@gmail.com"
copyright:           "CC0"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/runeksvendsen/crypto-liquidity-db#readme>

default-extensions:
- FlexibleContexts
- StrictData

dependencies:
- base >= 4.7 && < 5
- protolude

ghc-options:
  - -Wall
  - -fno-warn-unused-imports

library:
  source-dirs: src
  dependencies:
  - crypto-orderbook-db
  - beam-core
  - beam-postgres
  - time >= 1.9
  - text
  - vector
  # App/exe
  - order-graph
  - stm
  - async
  - postgresql-simple
  - monad-control
  - transformers-base
  - bytestring
  - containers
  - transformers
  - mtl
  - pqueue
  - lrucache
  - beam-automigrate
  - resource-pool
  - retry
  - logging
  - ansi-terminal
  - pretty-show

executables:
  crypto-liquidity-db-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    dependencies:
    - crypto-liquidity-db
  beam-servant-test:
    main:                Main.hs
    source-dirs:         test-app
    ghc-options:
    - -O2
    dependencies:
    - crypto-liquidity-db
    - crypto-orderbook-db
    - order-graph
    - servant
    - servant-server
    - aeson
    - beam-postgres
    - warp

tests:
  crypto-liquidity-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-liquidity-db
