name: build & test

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!.github/workflows/cabal-in-nix-shell.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose pull
        run: docker-compose pull --include-deps

      - name: Use cached build image
        run: sed -i 's/FROM ubuntu:16.04 as builder/FROM runeks86\/crypto-liquidity-db-build-cache:0.3 as builder/' Dockerfile

      - name: docker-compose build
        run: docker-compose build

      - name: docker-compose test
        run: docker-compose up --exit-code-from liquidity-service-test

      - name: Save docker image
        run: |
          IMAGE_ID=$(docker images | awk 'NR==2' | awk '{print $3}')
          docker save "$IMAGE_ID" -o docker-image.tar

      - name: Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image.tar
          path: docker-image.tar
