name: Docker build

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker build
        run: docker build .
