name: build & test

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker-compose test
        run: docker-compose up --exit-code-from liquidity-service-test

      - name: Save docker image
        run: |
          IMAGE_ID=$(docker images | awk 'NR==2' | awk '{print $3}')
          docker save "$IMAGE_ID" -o docker-image.tar

      - name: Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image.tar
          path: docker-image.tar
