name: Docker build

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      - name: Pull Docker images
        run: docker-compose pull

      # source: https://github.com/satackey/action-docker-layer-caching#docker-compose
      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: docker-compose build
        run: docker-compose up -d --build