name: build & test

on:
  push:
    paths:
      - '**'
      - '!README.md'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose pull
        run: docker-compose pull --include-deps

      - name: docker-compose build
        run: docker-compose build

      - name: docker-compose test
        run: docker-compose up --exit-code-from liquidity-service-test
